config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  mount Ckeditor::Engine => '/ckeditor'
  authenticate do
    mount Sidekiq::Web => '/sidekiq'
  end
  root to: "admin/dashboard#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :restaurant_admins, skip: :all
  devise_for :company_admins, skip: :all
  devise_for :company_users, skip: :all
  devise_for :company_managers, skip: :all
  devise_for :unsubsidized_users, skip: :all
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
        confirmations: 'api/v1/auth/confirmations',
        sessions:  'api/v1/auth/sessions',
        passwords: 'api/v1/auth/passwords',
        unlocks: 'api/v1/auth/unlocks'
      }
      namespace :dashboard do
        resources :meetings do
          collection do
            get :your_deliveries
            get :delivery_requests
            get :your_locations
            get :other_locations
          end
        end
      end
      resources :announcements, only: [:index]
      namespace :vendor do
        resources :shortened_urls, only: [:show]
        # get '/:id' => "shortened_urls#show"
        resources :restaurants do
          resources :menus, only: [:index, :update] do
            put :relate_fooditem
            post :fooditems
            post :dishsizes
          end
          collection do
            get :summary_excel
          end
          member do
            get :meetings
            get 'meetings/:meeting_id/orders', to: 'restaurants#orders'
            get 'meetings/:meeting_id/get_summary_pdf', to: 'restaurants#get_summary_pdf'
            # get 'meetings/:meeting_id/summary_excel', to: 'restaurants#summary_excel'
            get 'meetings/:meeting_id/get_labels', to: 'restaurants#get_labels'
            put 'meetings/:meeting_id/orders_status', to: 'restaurants#orders_status'
            # get :delivery_dates
            put :update_settings
            get :admins
          end
          resources :reports, only: [:index]
          resources :billings, only: [:index, :show]
          resources :invoices, only: [:index, :show, :update] do
            get :forward_invoice
            post :forwarded_invoice
          end
          collection do
            post :zendesk_support
            get :cuisines
            put :update_admin
          end
        end
        resources :drivers do
          collection do
            post :meeting_driver
          end
        end
        resources :schedules, only: [] do
          member do
            put 'acknowledge', to: 'restaurants#acknowledge_schedule'
          end
        end
        get '/freshdesk_logs', to: 'logs#freshdesk_logs'
      end
      resources :searches, only: [:index] do
        get :restaurants, on: :collection
      end
      resources :reports, only: [:index]
      get '/cuisines', to: 'cuisines#index'
      #get 'companies/addresses', to: 'companies#addresses'
      #get 'companies/fields', to: 'companies#custom_fields'
      get 'company', to: 'companies#index'
      #get 'companies/orders/show/:runningmenu_id/:address_id/:order_type/:ordered_at', to: 'orders#company_orders_show'
      # get 'companies/orders/show/:runningmenu_id/:address_id/:order_type/:ordered_at/:email', to: 'orders#company_orders_show'
      # post 'companies/orders/show/:runningmenu_id/:address_id/:order_type/:ordered_at/:email', to: 'orders#company_orders_show'
      # get 'checkrequests/:delivery_at/:type/:address_id', to: 'schedules#checkrequests'
      # get '/menu_change_request/:delivery_at/:type/:address_id', to: 'schedules#request_menu_change'
      # get 'meetings', to: 'schedules#meetings'
      #get 'all_schedules', to: 'schedules#all_schedules'
      # get 'pendingrequests', to: 'schedules#pendingrequests'
      get 'orders_ratings', to: 'orders#order_ratings'
      get 'restaurants_cuisines', to: 'cuisines#restaurants_cuisines'
      # post 'schedule_request/create', to: 'menus#create_schedule_request'
      # post 'stripe/connect', to: 'stripe#connect'
      get 'stripe/connect', to: 'stripe#connect'
      get 'stripe/login', to: 'stripe#login'
      get 'stripe/completion', to: 'stripe#completion'
      post 'referrals/send_invite', to: 'referrals#invite_referred'

      resources :companies, only: [:update] do
        collection do
          put :billing
          get :billings
          get :future_meeting
          get :fields
          get :addresses
          get :meetings
          get :childs
          get :send_invoice_email
        end
      end
      resources :menus, only: [] do
        collection do
          get :schedules
        end
      end
      resources :addresses, only: [] do
        get :menus
      end
      resources :orders, only: [:show, :update, :index] do
        member do
          get :fooditem
          post :rating
          get :restaurant
          get ':email', to: 'orders#show'
          delete :cancel
        end
        collection do
          post :clone
          get :cancelled
        end
      end

      resources :schedules, only: [:show, :update, :create] do
        member do
          get :orders
          get :notify_users
          delete :cancel
          get :recent
        end
        collection do
          get :cancelled
          get :delivery_dates
        end
      end

      # resources :schedule_requests, only: [:create, :update]
      # resources :schedules, only: [:index] do
      resources :schedules, only: [] do
        get 'active_orders', to: 'menus#orders'
        get 'buffet_orders', to: 'orders#buffet'
        # resources :addresses, only: [] do
        resources :menus, only: [:index] do
          get :dynamic_sections, on: :collection
        end
        # end
        resources :orders, only: [:create]

        resources :share_meetings do
          collection do
            post :by_token
            post :generate_token
            post :add_customer
          end
          get :resend_invite
        end
      end

      resources :childs do
        member do
          get :company_admins
          get :company_locations
        end
        collection do
          put :update_user
        end
      end

      resources :user_requests do
        member do
          get :send_invite
        end
      end
      resources :users, only: [:index, :destroy, :update] do
        member do
          post :send_invite
        end
        collection do
          get :profile
          put :profile
          post :invite
          put :invite
          post :send_vendor_invite
          get :search
        end
      end
      resources :fooditems, only: [] do
        resources :favorites, only: [:create] do
          delete "", to: 'favorites#destroy', on: :collection
        end
      end
    end
  end

  namespace :admin do
    resources :email_logs
    get 'schedules/:id/address/:address_id/acknowledge', to: 'acknowledges#acknowledge'
    get '/onfleet/webhook', to: 'webhooks#validate'
    get '/onfleet/webhook/driver_arrival', to: 'webhooks#validate'
    get '/onfleet/webhook/driver_eta', to: 'webhooks#validate'
    get '/onfleet/webhook/task_started', to: 'webhooks#validate'
    post '/onfleet/webhook', to: 'webhooks#receive'
    post '/onfleet/webhook/driver_arrival', to: 'webhooks#driver_arrival'
    post '/onfleet/webhook/driver_eta', to: 'webhooks#driver_eta'
    post '/onfleet/webhook/task_started', to: 'webhooks#task_started'
    get '/twilio/webhook', to: 'webhooks#sms_receive'
    get '/restaurants/twilio/webhook', to: 'webhooks#restaurants_sms'
    # post '/twilio_fax_status/webhook', to: 'webhooks#fax_status_callback'
    # post '/twilio_sms_status/webhook', to: 'webhooks#sms_status_callback'
    post '/freshdesk/webhook', to: 'webhooks#freshdesk_ticket_receive'
    get '/quickbooks_oauth/webhook', to: 'webhooks#quickbooks_oauth_callback'
    resources :restaurants do
      resources :addresses
      resources :gmenus do
        member do
          get :relate_gfooditems
          post :related_gfooditems
          get :relate_goptionsets
          post :related_goptionsets
        end
        collection do
          post :import
        end
      end
      resources :addresses do
        resources :menus do
          member do
            get :relate_fooditems
            post :related_fooditems
            get :relate_optionsets
            get :relate_dishsizes
            post :related_optionsets
            post :related_dishsizes
            get :fooditems_nutritions
            get :options_nutritions
          end
          collection do
            post :import
          end
        end
      end
    end
  end

  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/helpers/order_helper.rb
module OrderHelper
  def self.orders_billing(orders)
    billing = Hash.new
    billing["enable_self_service"] = false
    billing["sub_total"] = billing["sale_tax_percentage"] = billing["sale_tax"] = billing["discount_percentage"] = billing["commission"] = billing["delivery_cost"] = billing["payout_total"] = 0
    
    return billing if orders.blank?
    # address = RestaurantAddress.find_by_id address_id
    # buffet_menu_type = (orders.class.equal?(Array) ? Runningmenu.menu_types.keys[orders.first.menu_type] : orders.last.runningmenu.menu_type) == 'buffet'
    if orders.class.equal?(Array)
      # option_total = (sprintf "%.2f", (orders.map{|o| o.active? && o.options.present? ? o.options_price * o.quantity : 0 }.sum)).to_f
      # food_total = (sprintf "%.2f", (orders.map{|o| o.order_status == 'active' || o.order_status.empty? ? o.food_price_total : 0}.sum)).to_f
      food_total = orders.map{|o| o.order_status == 'active' || o.order_status.empty? ? o.food_price_total : 0}.sum
      # billing["discount_percentage"] = buffet_menu_type && (orders.sum(&:quantity) >= address.items_count || food_total >= address.minimum_discount_price) ? (address.add_contract_commission ? (address.discount_percentage + address.buffet_commission) : address.buffet_commission) : (buffet_menu_type ? 0 : address.discount_percentage)
      # billing["sale_tax_percentage"] = TaxRate.exists?(zip: address.zip) ? TaxRate.find_by(zip: address.zip).estimated_combined_rate : 0.0925
      # billing["sub_total"] = food_total
      # billing["commission"] = (sprintf "%.2f", ((billing["sub_total"] * billing["discount_percentage"])/100) ).to_f
      # billing["sale_tax"] = (sprintf "%.2f", (billing["sub_total"] * billing["sale_tax_percentage"])).to_f
      # billing["payout_total"] = sprintf('%.2f', (billing["sub_total"] - billing["commission"] + billing["sale_tax"]))
      # billing
    else
      food_total = orders.map{|o| o.status == 'active' ? o.food_price_total : 0}.sum
      # billing["discount_percentage"] = buffet_menu_type && (orders.sum(&:quantity) >= address.items_count || food_total >= address.minimum_discount_price) ? (address.add_contract_commission ? (address.discount_percentage + address.buffet_commission) : address.buffet_commission) : (buffet_menu_type ? 0 : address.discount_percentage)
      # billing["sale_tax_percentage"] = TaxRate.exists?(zip: address.zip) ? TaxRate.find_by(zip: address.zip).estimated_combined_rate : 0.0925
      # billing["sub_total"] = food_total
      # billing["commission"] = (sprintf "%.2f", ((billing["sub_total"] * billing["discount_percentage"])/100) ).to_f
      # billing["sale_tax"] = (sprintf "%.2f", (billing["sub_total"] * billing["sale_tax_percentage"])).to_f
      # billing["payout_total"] = sprintf('%.2f', (billing["sub_total"] - billing["commission"] + billing["sale_tax"]))
      # billing
    end
    restaurant_address = RestaurantAddress.find(orders.first.restaurant_address_id)
    runningmenu = Runningmenu.find(orders.first.runningmenu_id)
    delivery_cost = restaurant_address.enable_self_service && runningmenu.delivery? ? restaurant_address.delivery_cost : 0.0
    billing["enable_self_service"] = restaurant_address.enable_self_service
    billing["delivery_meeting"] = runningmenu.delivery?
    billing["sub_total"] = food_total
    billing["sale_tax_percentage"] = orders.blank? ? "" : orders.first.sales_tax_rate*100
    billing["sale_tax"] = orders.sum(&:sales_tax)&.round(2)
    billing["discount_percentage"] = food_total > 0 ? (orders.sum(&:restaurant_commission)/food_total * 100)&.round(2) : 0.0
    billing["commission"] = orders.sum(&:restaurant_commission)&.round(2)
    billing["delivery_cost"] = delivery_cost
    billing["payout_total"] = orders.sum(&:restaurant_payout)&.round(2) + delivery_cost
    billing
  end
end

app/views/admin/orders/_order_summary.html.erb
<%= form_tag('/admin/order_report', method: :get, id: "order_report_form") do %>
  <div class="row">
    <div class="col">
      Scheduler ID: <%= text_field_tag "s", params['s'] %>
    </div>
    <div class="col">
      <%= submit_tag 'Submit' %>
    </div>
  </div>
<% end %>
<% if orders.present? %>
  <table border="0" cellspacing="0" cellpadding="0" id="index_table_cuisines" class="index_table index" paginator="true">
    <thead>
      <tr>
        <th class="admin-devcol col-name">User Name</th>
        <th class="admin-devcol col-name">Email</th>
        <th class="admin-devcol col-name">Company Name</th>
        <th class="admin-devcol col-name">Company location</th>
        <th class="admin-devcol col-name">Restaurant Name</th>
        <th class="admin-devcol col-name">Item Name</th>
        <th class="admin-devcol col-name">Options</th>
        <th class="admin-devcol col-name">Extra Instructions</th>
        <th class="admin-devcol col-description">Quantity</th>
        <th class="admin-devcol col-name">Delivery Date & Time</th>
        <% if grouping %>
          <th class="admin-devcol col-name">Group</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% orders.each do |order| %>
        <tr class="odd">
          <%
            usernames = order.user_name.split(",")
            emails = order.email.split(",")
          %>
          <td class="col col-name"><%= usernames.count < 2 ? usernames.join() : "" %></td>
          <td class="col col-name"><%= emails.count < 2 ? emails.join() : "" %></td>
          <td class="col col-name"><%= @runningmenu.company.name %></td>
          <td class="col col-name"><%= @runningmenu.address.address_line %></td>
          <td class="col col-name"><%= order.restaurant_name %></td>
          <td class="col col-name"><%= order.fooditem_name %></td>
          <td class="col col-name"><%= order.options&.split(', ')&.map{|o| o.split('$')[0]}&.join(', ') %></td>
          <td class="col col-name"><%= order.remarks %></td>
          <td class="col col-name"><%= order.quantity %></td>
          <td class="col col-name"><%= @runningmenu.delivery_at_timezone.strftime('%B %d, %Y %I:%M%p') %></td>
          <% if grouping %>
            <td class="col col-name"><%= order.order_group %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <div id="index_footer">
    <div class="download_links">
      <span>Download:</span>
      <%= link_to "CSV", admin_order_report_csv_path( format: :csv, s: params[:s] )%> |
      <%= link_to "Summary PDF", admin_order_report_pdf_path( format: :pdf, s: params[:s], buffet: @runningmenu.buffet?)%> |
      <%= link_to "Labels CSV", admin_order_report_labelspdf_path( format: :pdf, s: params[:s] )%>|
      <%= link_to "Labels Doc", admin_order_report_docx_path(format: :docx, s: params[:s]) %>
    </div>
  </div>
<% end %>

app/views/admin/orders/admin_buffet_summary.html.erb
<style>
  .newContainer {
    max-width: 800px;
    margin: 0 auto;
    font-family: Arial, Helvetica, sans-serif;
  }
  .newContainer .newHeader {
    text-align: center;
  }
  .newContainer .newHeader .logo{
    width: 50px;margin: 0 auto; display: block; margin-bottom: 30px;
  }
  .newContainer .newHeader .badge {
    position: relative;
    margin-left: 10px;
    background: #6f6f6f;
    font-size: 12px;
    font-weight: normal;
    padding: 2px 8px;
    border-radius: 15px;
    color: #ffffff;
  }
  .newContainer .newHeader .address {
    color: #6f6f6f;
    font-weight: normal;
    font-size: 12px;
    margin-top: -10;
  }
  .newContainer .newHeader table {
    margin: 0 auto;
    font-size: 13px;
  }
  .applyBold {
    font-weight: bold;
  }
  .applyDarkGrayColor {
    color: #6f6f6f;
  }
  .newContainer .block_ {
    border: 1px solid rgb(192, 192, 192);
    border-radius: 5px;
    overflow: hidden;
    display: table;
    margin-bottom: 10px;
  }
  .newContainer .block_ .col_4 {
    /* max-width: 33.333%; */
    width: 100%;
    display: table-cell;
    vertical-align: top;
  }
  .newContainer .block_ .col_8 {
    /* max-width: 95%; */
    width: 95%;
    padding: 15px;
    display: table-cell;
    vertical-align: top;
  }
  .newContainer .block_ .col_8 h3 {
    font-size: 1.25em;
    margin: 7px auto;
  }
  .newContainer .block_ .col_8 p {
    margin-top: 10px;
    color: #848484;
    font-size: .8em;
    margin-bottom: 0;
  }
  p strong, p b {
    font-size: .8em;
    color: #848484;
  }
  .newContainer .block_ .col_8 .options_ {
    margin-top: 5px;
  }
  .newContainer .block_ .col_8 .options_ span {
    background: rgb(226, 226, 226);
    padding: 5px 7px;
    margin-right: 7px;
    margin-bottom: 5px;
    display: inline-block;
    font-size: .8em;
    border-radius: 15px;
  }
  .img_size{
    object-fit: contain;
  }

  .float{
    float: left;
    overflow: hidden;
  }
  div.block_ { page-break-inside:avoid }
</style>
<div class="newContainer">
  <div class="newHeader">
    <!-- <img src="https://app.chowmill.com/imgs/chowmill-logo.png" class="logo"> -->
    <%= image_tag wicked_pdf_asset_base64("logo.png"), :style => "width: 40px;", alt: 'logo' %>
    <h3><%= runningmenu.runningmenu_name.capitalize %><span class="badge"><%= runningmenu.runningmenu_type.capitalize + " " + runningmenu.menu_type.capitalize %></span></h3>
    <h6 class="address"><%= runningmenu.address.address_line %></h6>
    <table cellpadding="5" cellspacing="0">
      <tr>
        <td align="right" class="applyBold"><%= runningmenu.delivery_at_timezone.strftime("%a %b %d at %-l:%M %P") %></td>
        <td>&nbsp;</td>
        <td align="right" class="applyBold">Buffet</td>
      </tr>
      <tr>
        <td align="right" class="applyDarkGrayColor applyBold">Delivery Time</td>
        <td>&nbsp;</td>
        <td align="left" class="applyDarkGrayColor applyBold">Style</td>
      </tr>
    </table>
  </div>
  <br>

  <% orders.each do |order| %>
    <div class="block_">
      <div class="col_4 float">
          <%#= wicked_pdf_image_tag(order.fooditem.image.present? ? order.fooditem.image.medium.url.gsub("https:", "") : "fooditem.png", height: '150', width: '280', class: 'img_size', alt: '') %>
          <% if order.fooditem.image.present? %>
            <%= wicked_pdf_image_tag(order.fooditem.image.medium.url.gsub("https:", ""), height: '150', width: '280', class: 'img_size', alt: 'food-image') %>
          <% else %>
            <%= image_tag wicked_pdf_asset_base64("fooditem.png"), :style => "width: 280px;height: 150px;", class: 'img_size', alt: 'food-image' %>
          <% end %>
      </div>
      <div class="col_8">
        <h3><%= order.fooditem.sections.last.section_type.gsub("_", " ").capitalize %>: <%= order.fooditem.name.capitalize %> </h3>
        <p><%= truncate(order.fooditem.description.capitalize, length: 165) %><br>
          <% options = order.optionsets_orders.joins(:options_orders => :option).where("options.description IS NOT NULL").pluck("options.description").to_sentence %>
          <% if options.present? %>
            <strong>Option: <%= options %></strong>
          <% end %>
        </p>
        <div class="options_">
          <% (order.fooditem.dietaries.pluck(:name) + order.fooditem.ingredients.pluck(:name)).each do |diet_ing|%>
            <span><%= diet_ing %></span>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

</div>

app/views/admin/orders/labelspdf.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
    <title><%= orders.first.short_code  + "-" if orders.first.short_code.present? %> <%= orders.first.restaurant_name if orders.present?%>-<%= delivery_at.to_date %></title>


    <style>
        body {
            font-family: Arial, sans-serif;
            padding:0;
            margin:0;
        }

        .logo {
            width: 20px;
            position: absolute;
            right: 10px;
            bottom: 2px;
        }
        .logo img {
            width: 100%;
        }

        .red {
            color: red
        }
        .caps {
            text-transform: uppercase;
        }
        .bold {
            font-weight: bold;
        }
        td {
          width:240px;
          height:144px;
          overflow:hidden;
          padding: 10px;
          vertical-align: top;
          width:33%;
          position: relative;
        }
        .fixed_block__ {
          width: 240px;
          height: 144px;
          overflow: hidden;
          position: relative;
          padding:3px;
        }
        h1,h2,h3,h4,h5,h6 {margin: 0}

        small {
            font-size: 70%;
        }
    </style>
</head>
<body style="padding: 12px;">
<table style="width:100%;">
    <% if orders.present? %>
        <tr>
        <% counter = 1 %>
        <% basicinfo = 1 %>
      <% orders.each do |order| %>

        <% (1..order.quantity).each do |val| %>
            <% if basicinfo == 1 %>
                <td class="red caps bold">
                  <div class="fixed_block__">
                    <%= orders.first.restaurant_name %> <br>
                    DELIVERY DATE: <%= delivery_at %><br>
                    <%= orders.map{|order| order.quantity}.sum %> of Items<br>

                    <h1 class="logo">
                      <%= image_tag wicked_pdf_asset_base64("logo.png") %>
                    </h1>
                  </div>
                </td>
                <% counter += 1 %>
                <% basicinfo += 1 %>
            <% end %>
            <td width="33%">
              <div class="fixed_block__">
                <% order.fooditem_name.gsub! 'and', '&' %>
                <% order.fooditem_name.gsub! 'with', 'w/' %>
                <% order.fooditem_name.gsub! 'Vegetarian', 'V' %>
                <% order.fooditem_description.gsub! 'and', '&' %>
                <% order.fooditem_description.gsub! 'with', 'w/' %>
                <% order.fooditem_name.gsub! 'Vegetarian', 'V' %>
                <h5><%= order.fooditem_name.truncate_words(12, omission: '...') %></h5>
                <small><%= order.fooditem_description.truncate_words(15, omission: '...') if order.fooditem_description.present? %></small>
                <h6 class="red"><%= order.options %></h6>
                <h6 class="red"> <%= order.remarks if order.remarks.present? %></h6>
                <small><%= order.short_code %></small>

                <h1 class="logo">
                    <%= image_tag wicked_pdf_asset_base64("logo.png") %>
                </h1>
              </div>
            </td>
            <% if counter == 3 %>
                <% counter = 1%>
                </tr>
                <tr>
            <% else %>
                <% counter += 1 %>
            <% end %>
        <% end %>
      <% end %>
    <% end %>
</table>


</body>
</html>

app/views/admin/orders/userlabelspdf.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
    <title><%= orders.first.short_code %>-<%= orders.first.restaurant_name if orders.present?%>-<%= delivery_at.to_date %></title>


    <style>
      body {
          font-family: Arial, sans-serif;
          padding:0;
          margin:0;
      }

      .logo {
          width: 20px;
          position: absolute;
          right: 10px;
          bottom: 2px;
      }
      .logo img {
          width: 100%;
      }

      .red {
          color: red
      }
      .caps {
          text-transform: uppercase;
      }
      .bold {
          font-weight: bold;
      }
      td {
        width:240px;
        height:144px;
        overflow:hidden;
        padding: 10px;
        vertical-align: top;
        width:33%;
        position: relative;
      }
      .fixed_block__ {
        width: 240px;
        height: 144px;
        overflow: hidden;
        position: relative;
        padding:3px;
      }
      h1,h2,h3,h4,h5,h6 {margin: 0}

      small {
          font-size: 70%;
      }
    </style>
</head>
<body style="padding: 12px;">
<table style="width:100%">
  <% if orders.present? %>
      <tr>
      <% counter = 1 %>
      <% basicinfo = 1 %>
    <% orders.each do |order| %>

      <% (1..order.quantity).each do |val| %>
          <% if basicinfo == 1 %>
              <td class="red caps bold">
                <div class="fixed_block__">
                  <%= orders.first.restaurant_name %> <br>
                  DELIVERY DATE: <%= delivery_at %><br>
                  <%= orders.map{|order| order.quantity}.sum %> of Items<br>

                  <h1 class="logo">
                    <%= image_tag wicked_pdf_asset_base64("logo.png") %>
                  </h1>
                </div>
              </td>
              <% counter += 1 %>
              <% basicinfo += 1 %>
          <% end %>
          <td width="33%">
            <div class="fixed_block__">
              <% order.fooditem_name.gsub! 'and', '&' %>
              <% order.fooditem_name.gsub! 'with', 'w/' %>
              <% order.fooditem_name.gsub! 'Vegetarian', 'V' %>
              <h4><%= order.user_name.truncate_words(6, omission: '...') %></h4>
              <small><%= order.fooditem_name.truncate_words(12, omission: '...') %></small>
              <h6 class="red"><%= order.options %></h6>
              <h6 class="red"><%= order.remarks if order.remarks.present?%></h6>

              <small><%= order.short_code %></small>

              <h1 class="logo">
                  <%= image_tag wicked_pdf_asset_base64("logo.png"),alt: "logo" %>
              </h1>
            </div>
          </td>
          <% if counter == 3 %>
              <% counter = 1%>
              </tr>
              <tr>
          <% else %>
              <% counter += 1 %>
          <% end %>
      <% end %>
    <% end %>
  <% end %>
</table>


</body>
</html>