config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  mount Ckeditor::Engine => '/ckeditor'
  authenticate do
    mount Sidekiq::Web => '/sidekiq'
  end
  root to: "admin/dashboard#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :restaurant_admins, skip: :all
  devise_for :company_admins, skip: :all
  devise_for :company_users, skip: :all
  devise_for :company_managers, skip: :all
  devise_for :unsubsidized_users, skip: :all
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
        confirmations: 'api/v1/auth/confirmations',
        sessions:  'api/v1/auth/sessions',
        passwords: 'api/v1/auth/passwords',
        unlocks: 'api/v1/auth/unlocks'
      }
      namespace :dashboard do
        resources :meetings do
          collection do
            get :your_deliveries
            get :delivery_requests
            get :your_locations
            get :other_locations
          end
        end
      end
      resources :announcements, only: [:index]
      namespace :vendor do
        resources :shortened_urls, only: [:show]
        # get '/:id' => "shortened_urls#show"
        resources :restaurants do
          resources :menus, only: [:index, :update] do
            put :relate_fooditem
            post :fooditems
            post :dishsizes
          end
          collection do
            get :summary_excel
          end
          member do
            get :meetings
            get 'meetings/:meeting_id/orders', to: 'restaurants#orders'
            get 'meetings/:meeting_id/get_summary_pdf', to: 'restaurants#get_summary_pdf'
            # get 'meetings/:meeting_id/summary_excel', to: 'restaurants#summary_excel'
            get 'meetings/:meeting_id/get_labels', to: 'restaurants#get_labels'
            put 'meetings/:meeting_id/orders_status', to: 'restaurants#orders_status'
            # get :delivery_dates
            put :update_settings
            get :admins
          end
          resources :reports, only: [:index]
          resources :billings, only: [:index, :show]
          resources :invoices, only: [:index, :show, :update] do
            get :forward_invoice
            post :forwarded_invoice
          end
          collection do
            post :zendesk_support
            get :cuisines
            put :update_admin
          end
        end
        resources :drivers do
          collection do
            post :meeting_driver
          end
        end
        resources :schedules, only: [] do
          member do
            put 'acknowledge', to: 'restaurants#acknowledge_schedule'
          end
        end
        get '/freshdesk_logs', to: 'logs#freshdesk_logs'
      end
      resources :searches, only: [:index] do
        get :restaurants, on: :collection
      end
      resources :reports, only: [:index]
      get '/cuisines', to: 'cuisines#index'
      #get 'companies/addresses', to: 'companies#addresses'
      #get 'companies/fields', to: 'companies#custom_fields'
      get 'company', to: 'companies#index'
      #get 'companies/orders/show/:runningmenu_id/:address_id/:order_type/:ordered_at', to: 'orders#company_orders_show'
      # get 'companies/orders/show/:runningmenu_id/:address_id/:order_type/:ordered_at/:email', to: 'orders#company_orders_show'
      # post 'companies/orders/show/:runningmenu_id/:address_id/:order_type/:ordered_at/:email', to: 'orders#company_orders_show'
      # get 'checkrequests/:delivery_at/:type/:address_id', to: 'schedules#checkrequests'
      # get '/menu_change_request/:delivery_at/:type/:address_id', to: 'schedules#request_menu_change'
      # get 'meetings', to: 'schedules#meetings'
      #get 'all_schedules', to: 'schedules#all_schedules'
      # get 'pendingrequests', to: 'schedules#pendingrequests'
      get 'orders_ratings', to: 'orders#order_ratings'
      get 'restaurants_cuisines', to: 'cuisines#restaurants_cuisines'
      # post 'schedule_request/create', to: 'menus#create_schedule_request'
      # post 'stripe/connect', to: 'stripe#connect'
      get 'stripe/connect', to: 'stripe#connect'
      get 'stripe/login', to: 'stripe#login'
      get 'stripe/completion', to: 'stripe#completion'
      post 'referrals/send_invite', to: 'referrals#invite_referred'

      resources :companies, only: [:update] do
        collection do
          put :billing
          get :billings
          get :future_meeting
          get :fields
          get :addresses
          get :meetings
          get :childs
          get :send_invoice_email
        end
      end
      resources :menus, only: [] do
        collection do
          get :schedules
        end
      end
      resources :addresses, only: [] do
        get :menus
      end
      resources :orders, only: [:show, :update, :index] do
        member do
          get :fooditem
          post :rating
          get :restaurant
          get ':email', to: 'orders#show'
          delete :cancel
        end
        collection do
          post :clone
          get :cancelled
        end
      end

      resources :schedules, only: [:show, :update, :create] do
        member do
          get :orders
          get :notify_users
          delete :cancel
          get :recent
        end
        collection do
          get :cancelled
          get :delivery_dates
        end
      end

      # resources :schedule_requests, only: [:create, :update]
      # resources :schedules, only: [:index] do
      resources :schedules, only: [] do
        get 'active_orders', to: 'menus#orders'
        get 'buffet_orders', to: 'orders#buffet'
        # resources :addresses, only: [] do
        resources :menus, only: [:index] do
          get :dynamic_sections, on: :collection
        end
        # end
        resources :orders, only: [:create]

        resources :share_meetings do
          collection do
            post :by_token
            post :generate_token
            post :add_customer
          end
          get :resend_invite
        end
      end

      resources :childs do
        member do
          get :company_admins
          get :company_locations
        end
        collection do
          put :update_user
        end
      end

      resources :user_requests do
        member do
          get :send_invite
        end
      end
      resources :users, only: [:index, :destroy, :update] do
        member do
          post :send_invite
        end
        collection do
          get :profile
          put :profile
          post :invite
          put :invite
          post :send_vendor_invite
          get :search
        end
      end
      resources :fooditems, only: [] do
        resources :favorites, only: [:create] do
          delete "", to: 'favorites#destroy', on: :collection
        end
      end
    end
  end

  namespace :admin do
    resources :email_logs
    get 'schedules/:id/address/:address_id/acknowledge', to: 'acknowledges#acknowledge'
    get '/onfleet/webhook', to: 'webhooks#validate'
    get '/onfleet/webhook/driver_arrival', to: 'webhooks#validate'
    get '/onfleet/webhook/driver_eta', to: 'webhooks#validate'
    get '/onfleet/webhook/task_started', to: 'webhooks#validate'
    post '/onfleet/webhook', to: 'webhooks#receive'
    post '/onfleet/webhook/driver_arrival', to: 'webhooks#driver_arrival'
    post '/onfleet/webhook/driver_eta', to: 'webhooks#driver_eta'
    post '/onfleet/webhook/task_started', to: 'webhooks#task_started'
    get '/twilio/webhook', to: 'webhooks#sms_receive'
    get '/restaurants/twilio/webhook', to: 'webhooks#restaurants_sms'
    # post '/twilio_fax_status/webhook', to: 'webhooks#fax_status_callback'
    # post '/twilio_sms_status/webhook', to: 'webhooks#sms_status_callback'
    post '/freshdesk/webhook', to: 'webhooks#freshdesk_ticket_receive'
    get '/quickbooks_oauth/webhook', to: 'webhooks#quickbooks_oauth_callback'
    resources :restaurants do
      resources :addresses
      resources :gmenus do
        member do
          get :relate_gfooditems
          post :related_gfooditems
          get :relate_goptionsets
          post :related_goptionsets
        end
        collection do
          post :import
        end
      end
      resources :addresses do
        resources :menus do
          member do
            get :relate_fooditems
            post :related_fooditems
            get :relate_optionsets
            get :relate_dishsizes
            post :related_optionsets
            post :related_dishsizes
            get :fooditems_nutritions
            get :options_nutritions
          end
          collection do
            post :import
          end
        end
      end
    end
  end

  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/invoices/_filter_companies.html.erb
<%= form_tag(url, method: :post, id: "manual_invoice_form", autocomplete: "off" ) do %>
  <div class="row">
    <div class="col manual_invoice">
      Companies: <%= select_tag 'company_id', options_for_select(collection) %>
    </div>
    <div class="col">
      From: <%= text_field_tag "from", params['from'] %>
    </div>
    <div class="col manual_invoice">
      To: <%= text_field_tag "to", params['to'] %>
    </div>
    <div class="col">
      <%= submit_tag (defined?(recurrence_tag) && recurrence_tag) ? 'Create Schedulers' : 'Create Invoices' %>
    </div>
  </div>
<% end %>
<script type="text/javascript">
  $('#from, #to').keydown(function(event) {
    event.preventDefault();
  });

  <% if defined?(recurrence_tag) && recurrence_tag %>
    $( "#to" ).datetimepicker({
      format:'m/d/Y',
      minDate: 0,
      timepicker:false,
    });
    $( "#from" ).datetimepicker({
      format:'m/d/Y',
      minDate: 0,
      timepicker:false,
      onChangeDateTime:function(dp,$input){
        $("#to").datetimepicker({ minDate: $input.val() });
      }
    });
  <% else %>
      $( "#to" ).datetimepicker({
        format:'Y/m/d',
        maxDate: 0,
        timepicker:false,
      });
      $( "#from" ).datetimepicker({
        format:'Y/m/d',
        maxDate: 0,
        timepicker:false,
        onChangeDateTime:function(dp,$input){
          $("#to").datetimepicker({ minDate: $input.val() });
        }
      });
  <% end %>
  
  // $( "#to" ).datepicker({
  //   maxDate: 0,
  // });
  // $( "#from" ).datepicker({
  //   maxDate: 0,
  //   onClose: function( selectedDate ) {
  //     $( "#to" ).datepicker( "option", "minDate", selectedDate );
  //   }
  // });
  
  set_company_dates()

  function set_company_dates() {
    var c_id = $('#company_id').val();
    $.ajax({
      url:'/admin/invoices/company_current_date',
      data: {company_id: c_id},
      type:'get',
      success:function(data)
        {
          var date = data['company_current_date']
          set_datepickers(date)
        }
    });
  }

  $('#company_id').on("change", function() {
    $( "#from" ).val("");
    $( "#to" ).val("");
    var c_id = $(this).val();
    $.ajax({
      url:'/admin/invoices/company_current_date',
      data: {company_id: c_id},
      type:'get',
      success:function(data)
        {
          var date = data['company_current_date']
          set_datepickers(date)
        }
    });
  });

  function set_datepickers(date) {
    <% if defined?(recurrence_tag) && recurrence_tag %>
      $( "#from" ).datetimepicker({
        format:'m/d/Y',
        minDate: date,
        value: date,
        timepicker:false
      });
      $( "#to" ).datetimepicker({
        format:'m/d/Y',
        minDate: date,
        timepicker:false
      });
    <% else %>
      $( "#from" ).datetimepicker({
        format:'Y/m/d',
        maxDate: date,
        value: date,
        timepicker:false
      });
      $( "#to" ).datetimepicker({
        format:'Y/m/d',
        minDate: date,
        maxDate: date,
        timepicker:false
      });
    <% end %>
  }

</script>

app/views/admin/invoices/_forward_invoice.html.erb
<%= simple_form_for(@invoice, url: forwarded_invoice_admin_invoices_path, method: :post, :html => { id: 'forward_invoice_form', name: 'test'}) do |f| %>
  <%= f.input :recipients, required: "required", :input_html => {value: @invoice.approvers.exists? ? @invoice.approvers.map{ |a| a.email }.join(", ") : @invoice.invoice_email } %>
  <%= f.input :sender, as: :hidden, :input_html => { value: "finance@chowmill.com" } %>
  <%= f.input :cc, :input_html => { value: " finance@chowmill.com " } %>
  <%= f.input :subject, :input_html => { value: "Chowmill #{@invoice.charged_cc ? 'Receipt' : 'Invoice'} (#{@invoice.invoice_number}) for Delivery on #{@invoice.shipping_subject}" } %>
  <%= f.input :mail_body, as: :ckeditor, :input_html => { value: @forward_invoice_body.to_s.force_encoding("UTF-8") } %>
  <input type="hidden" id="invoiceID" name="invoice_id" value="<%= @invoice.id%>">
  <%= f.button :submit, "Send", class: "sendBtn" %>
<% end %>

app/views/admin/invoices/_line-items.html.erb
<table class="index_table index" >
	<thead>
	<tr>
	  <th class="sortable sorted-desc col col-id">Quantity</th>
	  <th class="sortable col col-name">Item</th>
	  <th class="col col-actions">Unit Price</th>
	  <th class="col col-actions">Amount</th>
    <th class="col col-actions">Discount</th>
	  <th>action</th>
	</tr>
	</thead>
	<tbody>
    <% orders = resource.orders.active %>
    <% orders.group_by{|o| o.runningmenu.runningmenu_name }.each do |key, value| %>
      <tr><td><%= key %>: <%= value.first.runningmenu.address.address_line %></td></tr>
      <% value.each do |order| %>
        <tr>
          <td><%= order.quantity %></td>
          <td><%= order.fooditem.name %></td>
          <td><%= number_with_precision(order.price, precision: 2) %></td>
          <td><%= number_with_precision((order.total_price - order.user_paid), precision: 2) %></td>
          <td><%= number_with_precision(order.discount, precision: 2) %></td>
          <td><%= button_to 'Edit', edit_admin_order_path(order.id), params: { a: 'invoice', b: order.invoice_id}, method: :get %></td>
        </tr>
      <% end %>
    <% end %>
    <% resource.line_items.each do |li| %>
      <tr>
        <td><%= li.quantity %></td>
        <td><%= li.item %></td>
        <td><%= number_with_precision(li.unit_price, precision: 2) %></td>
        <td><%= number_with_precision(li.amount, precision: 2) %></td>
        <td><%= number_with_precision(li.discount, precision: 2) %></td>
        <td><%= button_to 'Edit', edit_admin_invoice_path(resource.id), method: :get %></td>
      </tr>
    <% end %>
    <tr style="font-weight: bold">
      <td></td><td></td>
      <td>Total </td>
      <td><%= price_sum = orders.sum{|a| a.total_price - a.user_paid} + resource.line_items.sum{|li| li.amount} %></td>
      <td><%= discount_sum = orders.sum{|a| a.discount} + resource.line_items.sum{|li| li.discount} %></td>
    </tr>
    <tr style="font-weight: bold"><td></td><td></td><td>Discounted Total: </td><td><%= price_sum - discount_sum %></td><td></td></tr>
	</tbody>
</table>

app/views/admin/invoices/_manual_invoices_list.html.erb
<div>
  <table class="table">
    <thead>
      <th><strong>Invoice Number</strong></th>
      <th><strong>Company</strong></th>
      <th><strong>Bill To</strong></th>
      <th><strong>Ship To</strong></th>
      <th><strong>Total</strong></th>
      <th><strong>Delivery Fee</strong></th>
      <th><strong>Ship Range</strong></th>
      <th><strong>Due Date</strong></th>
      <th><strong>Current Date</strong></th>
      <th><strong>Actions</strong></th>
    </thead>
    <tbody>
      <% invoices.each do |invoice|%>
        <tr>
          <td><%= invoice.invoice_number %></td>
          <td><%= invoice.company.name %></td>
          <td><%= invoice.bill_to.html_safe%></td>
          <td><%= invoice.ship_to.html_safe%></td>
          <td><%= invoice.total_amount_due%></td>
          <td><%= invoice.line_items.sum(:amount)%></td>
          <td><%= invoice.shipping %></td>
          <td><%= invoice.due_date_timezone.strftime("%d/%m/%Y")%></td>
          <td><%= invoice.created_at_timezone.strftime("%d/%m/%Y %H:%M")%></td>
          <td><div class="table_actions"><%= link_to "PDF", generate_PDF_admin_invoice_path(id: invoice.id, format: :pdf), class: :member_link%></div></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/invoices/forward_invoice.js.erb
$('body').append(`
  <div class="customModal">
    <div class="contentWrapper animated">
      <div class="modalHeader">
        Forward Email
        <span class="modalClose"><em class="fa fa-times"></em></span>
      </div>
      <div class="modalBody">This is Body</div>
    </div>
  </div>
`);

$(".modalBody")
  .html("<%= escape_javascript(render 'forward_invoice') %>")
  .ready(function(){
    let encodedpdfID = $('#emailLogID').val();
    // alert( encodedpdfID );
    setTimeout(function(){
      let selectorOfPdfBtn = $('.cke_button.cke_button__save-to-pdf.cke_button_off');
      let checkEditorExist = selectorOfPdfBtn.length;

      selectorOfPdfBtn.removeAttr('href tabindex hidefocus role aria-labelledby aria-describedby onkeydown onfocus onclick aria-haspopup aria-disabled');
      selectorOfPdfBtn.attr('href', 'javascript://');
      selectorOfPdfBtn.attr ('onclick', 'window.open(\'/admin/email_logs/'+encodedpdfID+'/download_email_body\', \'_blank\')');

    }, 1500);
  });
;
$(document).on('click', '.modalClose', function(){
  $('body .customModal').remove();
});

$(document).on('click', '#forward_invoice_form .sendBtn', function(e){
  e.preventDefault();
  let checkErr = formValidate();
  if ( checkErr > 0 ) {
  } else {
    $('#forward_invoice_form').submit();
  }
});

function formValidate() {
  let err = 0;
  $(`#forward_invoice_form input:required, #forward_invoice_form select:required, #forward_invoice_form textarea:required`).each(function(){
    let checkVal = $(this).val();
    if ( checkVal === '' ) {
      $(this).css({'border':'1px solid red'});
      err++;
    } else {
      $(this).css({'border':'1px solid green'});
    }
  });
  return err;
}

$('.forwardInvoiceBtn, #forward_invoice_form').keydown(function(e){
  if(e.keyCode == 13) {
      e.preventDefault();
      return false;
    }
});

app/views/admin/invoices/forward_invoice_body.html.erb
            <%= render 'layouts/header' %>
            <p style="margin-left: auto; text-align: right; font: normal normal 500 16px/22px helvetica; letter-spacing: 0px; color: #FFFFFF; opacity: 1;">
            </p>
          </div>
        </td>
      </tr>
      <tr>
        <td>
          <div style=" background-color: #fff; box-shadow: 0px 3px 26px #0000000A; width: 80%; z-index: 1; margin: auto; border-radius:20px; padding: 30px 20px;">
            <table style="margin:30px auto 0 auto; width: 100%;">
              <tr>
                <td>
                  <p style="margin: 0; font: normal normal 500 22px/32px helvetica; letter-spacing: 0px; color: #1F1F1F; opacity: 1;text-align: center;">
                    Chowmill Invoice <%= invoice.invoice_number %> for Delivery on <%= invoice.shipping_subject%>
                  </p>
                </td>
              </tr>
            </table>
            <div style="display: flex;flex-direction: column; justify-content: center; align-items: center;">
            </div>
            <div style="margin-top: 30px;">
              <p style="margin: 0; font: normal normal normal 15px/18px helvetica; letter-spacing: 0px; color: #1F1F1F; opacity: 1;">
                Dear  <%= invoice.orders.last.runningmenu.company.name%>,
              </p>
              <%if invoice.charged_cc %>
              <p style="margin: 10px 0 0 0;font: normal normal normal 14px/22px helvetica; letter-spacing: 0px; color: #646464;">
                Please see attached due invoice(s) for service from
                <span style="margin: 0;font: normal normal 500 14px/22px helvetica; letter-spacing: 0px; color: #646464;"><%= invoice.shipping_body %>.</span>
              </p>
              <p style="margin:10px 0 0 0;font: normal normal normal 15px/21px helvetica; letter-spacing: 0px; color: #646464; opacity: 1; "> 
                Your card ending in <%= @card_last_four_digits %> has been charged
                <span style="margin: 0;font: normal normal 500 15px/21px helvetica; letter-spacing: 0px; color: #DC3545; opacity: 1; ">
                $<%= invoice.total_amount_due %>.
                </span>
              </p>
              <% else %>
              <p style="margin: 10px 0 0 0;font: normal normal normal 14px/22px helvetica; letter-spacing: 0px; color: #646464;">
                Please see attached due invoice(s) for service from
                <span style="margin: 0;font: normal normal 500 14px/22px helvetica; letter-spacing: 0px; color: #646464;"><%= invoice.shipping_body %>.</span>
              </p>
              <p style="margin: 10px 0 0 0;font: normal normal normal 14px/22px helvetica; letter-spacing: 0px; color: #646464;">
                We look forward to an early resolution.
              </p>
              <% end %>
              <p style="margin: 10px 0 0 0;font: normal normal normal 15px/21px helvetica; letter-spacing: 0px; color: #646464; opacity: 1;">
                Have a good day.
              </p>
              <p style="margin: 20px 0 0 0;font: normal normal normal 15px/21px helvetica; letter-spacing: 0px; color: #646464; opacity: 1; ">
                Best,
              </p>
              <p style="margin: 0;font: normal normal 500 15px/21px helvetica; letter-spacing: 0px; color: #DC3545; opacity: 1; ">
                Chowmill
              </p>
            </div>
          </div>
        </td>
      </tr>
    </table>
  </td>
</tr>
<%= render 'layouts/footer' %>

app/views/admin/invoices/invoice_header.html.erb
<!DOCTYPE html>
  <head>
    <title></title>
    <script>
      function number_pages() {
        var vars={};
        var x=document.location.search.substring(1).split('&');
        for(var i in x) {var z=x[i].split('=',2);vars[z[0]] = decodeURIComponent(z[1]);}
        var x=['frompage','topage','page','webpage','section','subsection','subsubsection'];
        for(var i in x) {
          var y = document.getElementsByClassName(x[i]);
          for(var j=0; j<y.length; ++j) y[j].textContent = vars[x[i]];
        }
        hideHeader()
      }
      function hideHeader() {
        var vars={};
        var x=document.location.search.substring(1).split('&');
        for(var i in x) {var z=x[i].split('=',2);vars[z[0]] = unescape(z[1]);}

        if(vars['page'] == 1){
          var elt = document.getElementById("headers_table");
          elt.parentNode.removeChild(elt);
        }
      }
    </script>
  </head>
  <body onload="number_pages()">
    <table style="width:100%;">
      <tr>
        <td style="width: 33%"><h1>Chowmill, Inc.</h1>
            458 Esther Ave, Campbell, CA 95008
            <br>Phone: (408) 883-9415<br>
            Email: support@chowmill.com
        </td>
        <td style="width: 33%; text-align: center;">
            <%= image_tag wicked_pdf_asset_base64("logo.png"), :style => "width: 40px;", alt: 'logo' %>
        </td>
        <td style="width: 33%; text-align: right;">
            <h1 style="color:silver"><%= @invoice.charged_cc ? 'RECEIPT' : 'INVOICE' %></h1>
            Invoice Number: <%= @invoice.invoice_number %><br>
            Current Date: <%= @invoice.created_at_timezone.strftime("%m/%d/%Y") %> <br>
            Page: <span class="page"></span> of <span class="topage"></span>
        </td>
      </tr>
    </table>
    <div style="max-height: 52px; overflow: hidden; width: 100%;">
      <% line_items_total_discount = @invoice.line_items.sum(:discount) %>
      <% order_column_sum = @invoice.orders.select("SUM(orders.discount) AS total_discount, SUM(orders.user_price) AS total_user_paid").to_a.first %>
      <table style="width: 100%" cellpadding="0" cellspacing="0" id="headers_table">
        <tbody>
          <tr>
            <!-- <td style="border:1px solid black; padding:8px; background: #eae8e8; font-weight: bold;">
              <div style="width:80px; font-size: 14px;">
                Delivery<br>Date
              </div>
            </td> -->
            <% colAvail = 0 %>
            <% if order_column_sum.total_discount > 0 || line_items_total_discount > 0 %>
              <% colAvail += 1 %>
            <% end %>
            <% if order_column_sum.total_user_paid > 0 %>
              <% order_column_sum.total_discount > 0 || line_items_total_discount > 0 ? colAvail += 1 : colAvail = 3%>
            <% end %>
            <td style="<%= colAvail == 0 ? "width: 18%;" : colAvail == 2 ? "width: 12.5%;" : colAvail == 3 ? "width: 15.5%;" : "width: 16.5%;" %>   border:1px solid black; padding:8px; background: #eae8e8; font-weight: bold;">
              <div style="font-size: 14px;">
                User
              </div>
            </td>
            <td style="<%= colAvail == 0 ? "width: 18%;" : colAvail == 2 ? "width: 13%;" : colAvail == 3 ? "width: 15.5%;" : "width: 16.5%;" %> border:1px solid black; padding:8px; background: #eae8e8; font-weight: bold;">
              <div style="font-size: 14px;">
                Restaurant
              </div>
            </td>
            <td style="<%= colAvail == 0 ? "width: 16%;" : colAvail == 2 ? "width: 9.5%;" : colAvail == 3 ? "width: 12.5%;" : "width: 14.5%;" %> border:1px solid black; padding:8px; background: #eae8e8; font-weight: bold;">
              <div style="font-size: 14px;">
                Qty.
              </div>
            </td>
            <td style="<%= colAvail == 0 ? "width: 16%;" : colAvail == 2 ? "width: 15.5%;" : colAvail == 3 ? "width: 16%;" : "width: 15.5%;" %> border:1px solid black; padding:8px; background: #eae8e8; font-weight: bold;">
              <div style=" font-size: 14px;">
                Item
              </div>
            </td>
            <td style="<%= colAvail == 0 ? "width: 8.5%;" : colAvail == 2 ? "width: 9%;" : colAvail == 3 ? "width: 8.5%;" : "width: 9%;" %> border:1px solid black; padding:8px; background: #eae8e8; font-weight: bold;">
              <div style="font-size: 14px;">
                Unit Price
              </div>
            </td>
            <td style="<%= colAvail == 0 ? "width: 9.5%;" : colAvail == 2 ? "width: 9%;" : "width: 9.5%;" %> border:1px solid black; padding:8px; background: #eae8e8; font-weight: bold;">
              <div style="font-size: 14px;">
                Company<br>Paid
              </div>
            </td>
            <% if order_column_sum.total_user_paid > 0 %>
              <td style="<%= colAvail == 2 ? "width: 9%;" : colAvail == 3 ? "width: 8.5%;" : "" %> border:1px solid black; padding:8px; background: #eae8e8; font-weight: bold;">
                <div style="font-size: 14px;">
                  User<br>Paid
                </div>
              </td>
            <% end %>
            <td style="border:1px solid black; padding:8px; background: #eae8e8; font-weight: bold;">
              <div style="<%= colAvail == 0 ? "width: 12%;" : colAvail == 2 ? "width: 9%;" : "" %>font-size: 14px;">
                Amount
              </div>
            </td>
            <% if order_column_sum.total_discount > 0 || line_items_total_discount > 0 %>
              <td style="<%= colAvail == 0 ? "" : colAvail == 2 ? "width: 11.5%;" : "" %>border:1px solid black; padding:8px; background: #eae8e8; font-weight: bold;">
                Discount
              </td>
            <% end %>
          </tr>

          <tr>
            <!-- <td style="border:1px solid white; background: #ffffff; color: #000;">
              <div style="word-break: break-all;">
                11/26/201912569
              </div>
            </td> -->
            <td style="border:1px solid white; background: #ffffff; color: #000;">
              <div style="width: 50%; word-break: break-all;">
                gh tv
              </div>
            </td>
            <td style="border:1px solid white; background: #ffffff; color: #000;">
              <div style="word-break: break-all;">
                Subway
              </div>
            </td>
            <td style="border:1px solid white; background: #ffffff; color: #000;">
              <div style="word-break: break-all;">
                5
              </div>
            </td>
            <td style="border:1px solid white; background: #ffffff; color: #000;">
              <div style=" word-break: break-all;">
                Chicken Tikka
              </div>
            </td>
            <td style="border:1px solid white; background: #ffffff; color: #000;">
              <div style="word-break: break-all;">
                $888.00
              </div>
            </td>
            <td style="border:1px solid white; background: #ffffff; color: #000;">
              <div style="word-break: break-all;">
                $888.88
              </div>
            </td>
            <% if order_column_sum.total_user_paid > 0 %>
              <td style="border:1px solid white; background: #ffffff; color: #000;">
                <div style="word-break: break-all;">
                  $888.88
                </div>
              </td>
            <% end %>
            <td style="border:1px solid white; background: #ffffff; color: #000;">
              <div style="word-break: break-all;">
                $65.00
              </div>
            </td>
            <% if order_column_sum.total_discount > 0 || line_items_total_discount > 0 %>
              <td style="border:1px solid white; background: #ffffff; color: #000;">
                <div style="word-break: break-all;">
                  $0.0
                </div>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>

  </body>
</html>