config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  mount Ckeditor::Engine => '/ckeditor'
  authenticate do
    mount Sidekiq::Web => '/sidekiq'
  end
  root to: "admin/dashboard#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :restaurant_admins, skip: :all
  devise_for :company_admins, skip: :all
  devise_for :company_users, skip: :all
  devise_for :company_managers, skip: :all
  devise_for :unsubsidized_users, skip: :all
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
        confirmations: 'api/v1/auth/confirmations',
        sessions:  'api/v1/auth/sessions',
        passwords: 'api/v1/auth/passwords',
        unlocks: 'api/v1/auth/unlocks'
      }
      namespace :dashboard do
        resources :meetings do
          collection do
            get :your_deliveries
            get :delivery_requests
            get :your_locations
            get :other_locations
          end
        end
      end
      resources :announcements, only: [:index]
      namespace :vendor do
        resources :shortened_urls, only: [:show]
        # get '/:id' => "shortened_urls#show"
        resources :restaurants do
          resources :menus, only: [:index, :update] do
            put :relate_fooditem
            post :fooditems
            post :dishsizes
          end
          collection do
            get :summary_excel
          end
          member do
            get :meetings
            get 'meetings/:meeting_id/orders', to: 'restaurants#orders'
            get 'meetings/:meeting_id/get_summary_pdf', to: 'restaurants#get_summary_pdf'
            # get 'meetings/:meeting_id/summary_excel', to: 'restaurants#summary_excel'
            get 'meetings/:meeting_id/get_labels', to: 'restaurants#get_labels'
            put 'meetings/:meeting_id/orders_status', to: 'restaurants#orders_status'
            # get :delivery_dates
            put :update_settings
            get :admins
          end
          resources :reports, only: [:index]
          resources :billings, only: [:index, :show]
          resources :invoices, only: [:index, :show, :update] do
            get :forward_invoice
            post :forwarded_invoice
          end
          collection do
            post :zendesk_support
            get :cuisines
            put :update_admin
          end
        end
        resources :drivers do
          collection do
            post :meeting_driver
          end
        end
        resources :schedules, only: [] do
          member do
            put 'acknowledge', to: 'restaurants#acknowledge_schedule'
          end
        end
        get '/freshdesk_logs', to: 'logs#freshdesk_logs'
      end
      resources :searches, only: [:index] do
        get :restaurants, on: :collection
      end
      resources :reports, only: [:index]
      get '/cuisines', to: 'cuisines#index'
      #get 'companies/addresses', to: 'companies#addresses'
      #get 'companies/fields', to: 'companies#custom_fields'
      get 'company', to: 'companies#index'
      #get 'companies/orders/show/:runningmenu_id/:address_id/:order_type/:ordered_at', to: 'orders#company_orders_show'
      # get 'companies/orders/show/:runningmenu_id/:address_id/:order_type/:ordered_at/:email', to: 'orders#company_orders_show'
      # post 'companies/orders/show/:runningmenu_id/:address_id/:order_type/:ordered_at/:email', to: 'orders#company_orders_show'
      # get 'checkrequests/:delivery_at/:type/:address_id', to: 'schedules#checkrequests'
      # get '/menu_change_request/:delivery_at/:type/:address_id', to: 'schedules#request_menu_change'
      # get 'meetings', to: 'schedules#meetings'
      #get 'all_schedules', to: 'schedules#all_schedules'
      # get 'pendingrequests', to: 'schedules#pendingrequests'
      get 'orders_ratings', to: 'orders#order_ratings'
      get 'restaurants_cuisines', to: 'cuisines#restaurants_cuisines'
      # post 'schedule_request/create', to: 'menus#create_schedule_request'
      # post 'stripe/connect', to: 'stripe#connect'
      get 'stripe/connect', to: 'stripe#connect'
      get 'stripe/login', to: 'stripe#login'
      get 'stripe/completion', to: 'stripe#completion'
      post 'referrals/send_invite', to: 'referrals#invite_referred'

      resources :companies, only: [:update] do
        collection do
          put :billing
          get :billings
          get :future_meeting
          get :fields
          get :addresses
          get :meetings
          get :childs
          get :send_invoice_email
        end
      end
      resources :menus, only: [] do
        collection do
          get :schedules
        end
      end
      resources :addresses, only: [] do
        get :menus
      end
      resources :orders, only: [:show, :update, :index] do
        member do
          get :fooditem
          post :rating
          get :restaurant
          get ':email', to: 'orders#show'
          delete :cancel
        end
        collection do
          post :clone
          get :cancelled
        end
      end

      resources :schedules, only: [:show, :update, :create] do
        member do
          get :orders
          get :notify_users
          delete :cancel
          get :recent
        end
        collection do
          get :cancelled
          get :delivery_dates
        end
      end

      # resources :schedule_requests, only: [:create, :update]
      # resources :schedules, only: [:index] do
      resources :schedules, only: [] do
        get 'active_orders', to: 'menus#orders'
        get 'buffet_orders', to: 'orders#buffet'
        # resources :addresses, only: [] do
        resources :menus, only: [:index] do
          get :dynamic_sections, on: :collection
        end
        # end
        resources :orders, only: [:create]

        resources :share_meetings do
          collection do
            post :by_token
            post :generate_token
            post :add_customer
          end
          get :resend_invite
        end
      end

      resources :childs do
        member do
          get :company_admins
          get :company_locations
        end
        collection do
          put :update_user
        end
      end

      resources :user_requests do
        member do
          get :send_invite
        end
      end
      resources :users, only: [:index, :destroy, :update] do
        member do
          post :send_invite
        end
        collection do
          get :profile
          put :profile
          post :invite
          put :invite
          post :send_vendor_invite
          get :search
        end
      end
      resources :fooditems, only: [] do
        resources :favorites, only: [:create] do
          delete "", to: 'favorites#destroy', on: :collection
        end
      end
    end
  end

  namespace :admin do
    resources :email_logs
    get 'schedules/:id/address/:address_id/acknowledge', to: 'acknowledges#acknowledge'
    get '/onfleet/webhook', to: 'webhooks#validate'
    get '/onfleet/webhook/driver_arrival', to: 'webhooks#validate'
    get '/onfleet/webhook/driver_eta', to: 'webhooks#validate'
    get '/onfleet/webhook/task_started', to: 'webhooks#validate'
    post '/onfleet/webhook', to: 'webhooks#receive'
    post '/onfleet/webhook/driver_arrival', to: 'webhooks#driver_arrival'
    post '/onfleet/webhook/driver_eta', to: 'webhooks#driver_eta'
    post '/onfleet/webhook/task_started', to: 'webhooks#task_started'
    get '/twilio/webhook', to: 'webhooks#sms_receive'
    get '/restaurants/twilio/webhook', to: 'webhooks#restaurants_sms'
    # post '/twilio_fax_status/webhook', to: 'webhooks#fax_status_callback'
    # post '/twilio_sms_status/webhook', to: 'webhooks#sms_status_callback'
    post '/freshdesk/webhook', to: 'webhooks#freshdesk_ticket_receive'
    get '/quickbooks_oauth/webhook', to: 'webhooks#quickbooks_oauth_callback'
    resources :restaurants do
      resources :addresses
      resources :gmenus do
        member do
          get :relate_gfooditems
          post :related_gfooditems
          get :relate_goptionsets
          post :related_goptionsets
        end
        collection do
          post :import
        end
      end
      resources :addresses do
        resources :menus do
          member do
            get :relate_fooditems
            post :related_fooditems
            get :relate_optionsets
            get :relate_dishsizes
            post :related_optionsets
            post :related_dishsizes
            get :fooditems_nutritions
            get :options_nutritions
          end
          collection do
            post :import
          end
        end
      end
    end
  end

  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/api/v1/menus_controller.rb
# app/controllers/api/v1/menus_controller.rb
class Api::V1::MenusController < Api::V1::ApiController
  skip_before_action :authenticate_active_user, if: lambda { params[:token].present? }
  before_action :set_share_meeting, if: lambda { params[:token].present? }
  before_action :set_runningmenu, only: [:index, :orders, :dynamic_sections]

  # GET /schedules/:id/addresses/:id/menus
  def index
    if @runningmenu.blank?
      error(E_INTERNAL, 'No menu defined')
    elsif params[:token].present? && @share_meeting.blank?
      error(E_INTERNAL, 'Meeting is not shared with this user')
    else
      p_params = "p_s3_base_url := 'https://#{ENV["S3_BUCKET_NAME"]}.s3.amazonaws.com'::TEXT, p_runningmenu_id := #{@runningmenu.id}, p_company_id := #{@runningmenu.company_id}"
      if current_member.present?
        p_params += ", p_current_user_id := #{current_member.id}"
      end
      if @share_meeting.present?
        p_params += ", p_share_meeting_id := #{@share_meeting.id}"
      end
      if params[:r].present?
        p_r = params[:r].join(",")
        p_params += ", p_r:= '#{p_r}'"
      end
      if params[:d].present?
        p_d = params[:d].join(",")
        p_params += ", p_d:= '#{p_d}'"
      end
      if params[:i].present?
        p_i = params[:i].join(",")
        p_params += ", p_i:= '#{p_i}'"
      end
      sql = "SELECT * FROM menus(#{p_params})"
      menus = ActiveRecord::Base.connection.execute(sql)
      render json: FetchMenus.call(current_member, menus.first["menus"])
    end
  end

  def dynamic_sections
    # binding.pry
  end

  # GET /menus/schedules
  def schedules
    # @schedule = Runningmenu.approved
    #   .where(company_id: current_member.company.id)
    #   .where(delivery_at: Time.current..Time.current + 28.days)
    #   .where('activation_at <= ?', Time.current)
    #   .order(delivery_at: :asc)
    #   .limit(1)

    # user = @share_meeting.present? ? @share_meeting.user : current_member
    # @company = @share_meeting.present? ? @share_meeting.runningmenu.company : current_member.company
    # @schedule = Runningmenu.approved.joins(:address)
    # .where('addresses.status = ?', Address.statuses[:active])
    # .where(user.company_user? ? 'runningmenus.hide_meeting = ?' : '', false )
    # .where(user.company_user? ? 'cutoff_at > ?' : 'admin_cutoff_at > ?',Time.current)
    # .where('delivery_at > ?', Time.current)
    # .where(company_id: @company.id)
    # .order("DATE(delivery_at) ASC")
    # .limit(1)

    # if @schedule.blank?
    #   @schedule = Runningmenu.approved.joins(:address)
    #   .where('addresses.status = ?', Address.statuses[:active])
    #   .where(user.company_user? ? 'runningmenus.hide_meeting = ?' : '', false )
    #   .where('DATE(delivery_at) >= ?', Time.current.to_date)
    #   .where(company_id: @company.id)
    #   .order("DATE(delivery_at) ASC")
    #   .limit(1)
    # end

    # @first_pending_delivery
    # if @schedule.blank?
    #   @first_pending_delivery = Runningmenu.pending.joins(:address)
    #   .where('addresses.status = ?', Address.statuses[:active])
    #   .where(user.company_user? ? 'runningmenus.hide_meeting = ?' : '', false )
    #   .where(company_id: @company.id)
    #   .where('delivery_at > ?', Time.current)
    #   .order("delivery_at ASC").pluck(:delivery_at).first
    # end

    # @schedules = Runningmenu.approved.joins(:address).select('runningmenus.id, runningmenu_type, address_id, delivery_at, DATE_FORMAT(delivery_at, "%Y-%m-%d") AS date, DATE_FORMAT(delivery_at, "%Y") AS year, DATE_FORMAT(delivery_at, "%m") AS month, DATE_FORMAT(delivery_at, "%d") AS day')
    #   .where('addresses.status = ?', Address.statuses[:active])
    #   .where(company_id: @company.id)
    #   .where(delivery_at: Time.current..Time.current + 28.days)
    #   .where('activation_at <= ?', Time.current)
    #   .order(delivery_at: :asc)

    # @booked = Order.active.select('runningmenu_id, orders.address_id, delivery_at, DATE_FORMAT(ordered_at, "%Y-%m-%d") AS date, DATE_FORMAT(ordered_at, "%Y") AS year, DATE_FORMAT(ordered_at, "%m") AS month, DATE_FORMAT(ordered_at, "%d") AS day')
    #   .joins(:runningmenu)
    #   .where(user_id: current_member.id)
    #   .where(company_id: current_member.company_id)
    #   .where(ordered_at: Time.current..Time.current + 28.days)
    #   .group(:runningmenu_id, :address_id, :date, :year, :month, :day)
  end

  private
  def set_runningmenu
    @runningmenu = Runningmenu.approved.find_by_slug params[:schedule_id]
    if @share_meeting.present?
      @runningmenu = @share_meeting.runningmenu
    end
    unless @runningmenu.present?
      error(E_INTERNAL, 'Unable to find scheduler')
    end
  end
  def set_share_meeting
    @share_meeting = ShareMeeting.find_by(token: params[:token])
    unless @share_meeting.present?
      error(E_INTERNAL, 'Unable to find shared meeting')
    end
  end
end

app/views/admin/menu/billing.html.erb
<div class="relate_menu__">
  <span>Billing</span>
</div>
<%= semantic_form_for @address, url: billing_information_admin_address_path(@address.id), builder: ActiveAdmin::FormBuilder, action:"edit" do |f| %>
  <%= f.input :items_count, label: 'Quantity', input_html: { min: '0', step: '1' }%>
  <%= f.input :minimum_discount_price, label: 'Minimum Amount($)', input_html: { min: '0', step: '0.1' }%>
  <%= f.input :buffet_commission, label: 'Discount(%)', input_html: { min: '0', step: '0.1' }%>
  <%= f.input :add_contract_commission%>
  <div class="relate_menu__">
    <br><br><span>Dish Sizes</span>
  </div>
  <%- f.has_many :dishsizes, heading: false do |ds|%>
    <%- ds.input :title%>
    <%- ds.input :description, :input_html => { :class => 'autogrow', :rows => 3, :cols => 20 }%>
    <%- ds.input :serve_count, input_html: { min: '0', step: '1' }%>
    <% unless ds.object.new_record? %>
      <%- ds.input :parent_status, as: :boolean, label: "Delete", :checked_value => "deleted", :unchecked_value => "active" %>
    <% end %>
  <% end %>
  <%= f.actions do %>
    <%= f.action :submit, :label => 'Save', :wrapper_html => { :style => "width:100px; margin-top: 20px;" }%>
  <% end %>
<%end%>

app/views/admin/menu/fooditems_nutritions.html.erb
<div class="relate_menu__">
  <span class="section_label__">Fooditems:</span>
  <span>Nutritional Facts</span>
</div>
<%= simple_form_for(resource, method: :put, url: admin_restaurant_address_menu_path) do |f| %>
  <%= f.simple_fields_for :fooditems do |fooditem| %>
    <% if fooditem.object.active? %>
      <div class="fooditems_nutritions_wrapper">
        <div class="fooditem_label__"><%= fooditem.object.name %>:</div>
        <div class="fields_wrapper">
          <%= fooditem.simple_fields_for :nutritional_facts, fooditem.object.nutritional_facts do |nutrition| %>
            <%= nutrition.input :value, label: nutrition.object.nutrition.name, input_html: { min: 0 } %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
  <%= f.submit 'Save', name: nil , :style => "width:100px; margin-top: 20px;" %>
  <%= link_to "Cancel", :back %>
<% end %>

app/views/admin/menu/options_nutritions.html.erb
<div class="relate_menu__">
  <span class="section_label__">Options:</span>
  <span>Nutritional Facts</span>
</div>
<%= simple_form_for(resource, method: :put, url: admin_restaurant_address_menu_path) do |f| %>
  <%= f.simple_fields_for :optionsets do |optionset| %>
    <%= optionset.simple_fields_for :options do |option| %>
      <% if option.object.active? %>      
        <div class="fooditems_nutritions_wrapper">
          <div class="fooditem_label__"><%= option.object.description %>:</div>
          <div class="fields_wrapper">
            <%= option.simple_fields_for :nutritional_facts, option.object.nutritional_facts do |nutrition| %>
              <%= nutrition.input :value, label: nutrition.object.nutrition.name, input_html: { min: 0 } %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
  <%= f.submit 'Save', name: nil , :style => "width:100px; margin-top: 20px;" %>
  <%= link_to "Cancel", :back %>
<% end %>

app/views/admin/menu/relate_dishsizes.html.erb
<div class="relate_menu__">
  <span class="section_label__">Fooditems:</span>
  <span>Dish Sizes</span>
</div>
<%= simple_form_for(resource, method: :post, url: related_dishsizes_admin_restaurant_address_menu_path) do |f| %>
  <%= f.simple_fields_for :fooditems do |fooditem| %>
    <% if fooditem.object.active? %>
      <span class="fooditem_label__"><%= fooditem.object.name %>:</span>
      <%= fooditem.simple_fields_for :dishsizes do |os| %>
        <%= os.select :dishsize_id, options_from_collection_for_select(resource.address.dishsizes.active, "id", "title", fooditem.object.dishsizes.active.pluck('id')), {:include_blank => true}, {:multiple => true} %>
      <% end %><br>
    <% end %>
  <% end %>
  <%= f.submit 'Save', name: nil , :style => "width:100px; margin-top: 20px;" %>
  <%= link_to "Cancel", :back %>
<% end %>

app/views/admin/menu/relate_fooditems.html.erb
<div class="relate_menu__">
  <span class="section_label__">Sections:</span>
  <span>Fooditems</span>
</div>
<%= simple_form_for(resource, method: :post, url: related_fooditems_admin_restaurant_address_menu_path) do |f| %>
  <%= f.simple_fields_for :sections do |section| %>
    <% if section.object.active? %>
      <span class="section_label__"><%= section.object.name %>:</span>
      <%= section.simple_fields_for :fooditems do |fs| %>
        <%= fs.select :fooditem_id, options_from_collection_for_select(resource.fooditems.active, "id", "name", section.object.fooditems.active.pluck('id')), {:include_blank => true}, {:multiple => true} %>
      <% end %><br>
    <% end %>
  <% end %>
  <%= f.submit 'Save', name: nil , :style => "width:100px; margin-top: 20px;" %>
  <%= link_to "Cancel", :back %>
<% end %>

app/views/admin/menu/relate_optionsets.html.erb
<div class="relate_menu__">
  <span class="section_label__">Fooditems:</span>
  <span>Option Sets</span>
</div>
<%= simple_form_for(resource, method: :post, url: related_optionsets_admin_restaurant_address_menu_path) do |f| %>
  <%= f.simple_fields_for :fooditems do |fooditem| %>
    <% if fooditem.object.active? %>
      <span class="fooditem_label__"><%= fooditem.object.name %>:</span>
      <%= fooditem.simple_fields_for :optionsets do |os| %>
        <%= os.select :optionset_id, options_from_collection_for_select(resource.optionsets.active, "id", "name", fooditem.object.optionsets.active.pluck('id')), {:include_blank => true}, {:multiple => true} %>
      <% end %><br>
    <% end %>
  <% end %>
  <%= f.submit 'Save', name: nil , :style => "width:100px; margin-top: 20px;" %>
  <%= link_to "Cancel", :back %>
<% end %>